### ISSUE TITLE
As of Today CSSLoader Desktop stopped working completely with the Steam Beta Update

### ISSUE THREAD

**Issue by Skyyblaze** [DeckThemes/CSSLoader-Desktop#27]
I was running on the Steam Beta Channel and as of today CSSLoader Desktop completely stopped theming anything in Steam. Reverting to the stable Steam client fixed it so something in the last beta must have broken theme injection. Is this being looked into already?

**Comment by Skyyblaze** [comment]
Ah I see, then I'll stay on stable and hope the themes get updated before the changes reach it.

**Comment by suchmememanyskill** [comment]
This will likely be fixed from cssloader's side; making every theme dev completely redo their entire theme is asking for trouble

**Comment by Skyyblaze** [comment]
Alright, thanks for the hard work!

**Comment by beebls** [comment]
Marking as closed as backend v2.1.0 and CSSLoader-Desktop v1.2.1 has added the 'Beta Steam CSS Translations' toggle to fix this

**Comment by Skyyblaze** [comment]
I just tested it and can confirm it works like a charm, thanks again!
