### ISSUE TITLE
Big picture steam not working in family share beta 

### ISSUE THREAD

**Issue by AngelMacias22** [DeckThemes/CSSLoader-Desktop#31]
Hello, I couldn't find any information about it, but the CSS loader desktop doesn't work in the new beta of Steam family share. I've tried activating the beta feature from CSS loader, but it still doesn't work.

**Comment by suchmememanyskill** [comment]
Are you running the latest dev build of cssloader? If not, that's probably the issue. A bit back steam changes the definition of the main ui tab, so stable cssloader can't inject into that.

**Comment by AngelMacias22** [comment]
> Are you running the latest dev build of cssloader? If not, that's probably the issue. A bit back steam changes the definition of the main ui tab, so stable cssloader can't inject into that.

Yes, i was using the last version 1.2.1

**Comment by suchmememanyskill** [comment]
That sounds like the latest release, not the latest developer build

**Comment by AngelMacias22** [comment]
> That sounds like the latest release, not the latest developer build

My bad sorry, I honestly don't know how to view the latest version from the developer, I don't have much knowledge about GitHub."

**Comment by iPablo** [comment]
@AngelMacias22 I had the same error using steam in Spanish on Asus Rog Ally, I'm waiting for this hotfix https://github.com/DeckThemes/SDH-CssLoader/pull/114

**Comment by kyc20010501** [comment]
I also have the same problem, the theme cannot take effect in the beta system of SteamDeck
