### ISSUE TITLE
CSSLoader-Desktop does not load on Ghost Spectre Windows 11

### ISSUE THREAD

**Issue by exzelis** [DeckThemes/CSSLoader-Desktop#33]
I'm using Ghost Spectre Windows 11 (Superlite SE) on Steam Deck. When I try to install CSSLoader-Desktop, the app does not launch even after reinstall and multiple restarts.

**Comment by suchmememanyskill** [comment]
You're probably on your own here; we're not supporting special snowflake repacks of windows. Only official versions of windows

**Comment by exzelis** [comment]
Fixed it. I've reinstalled the Ghost Spectre Superlite + SE + Def on Steam Deck. I just found out that Backend won't run without Windows Defender for some reason.
