### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Fireb3rt** [DeckThemes/CSSLoader-Desktop#36]
This repository appears to lack a license.  According to [GitHub Docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license): "no one may reproduce, distribute, or create derivative works from your work." Considering most other repositories in the DeckThemes organization contain a license, this looks like an oversight.

**Comment by beebls** [comment]
This is an oversight, thanks for pointing it out, I'll get to it later today
