### ISSUE TITLE
(Windows) nothing happens when I launch the app

### ISSUE THREAD

**Issue by GitMuslim** [DeckThemes/CSSLoader-Desktop#37]
I installed it but clicking on it starts it for 1 second (in taskbar) then it closes immediately

**Comment by suchmememanyskill** [comment]
Is windows defender killing it?

**Comment by GitMuslim** [comment]
doesn't seem like it

**Comment by suchmememanyskill** [comment]
Can you run this version and give me the console output? (Don't run it by double clicking, run it via cmd)

https://github.com/DeckThemes/SDH-CssLoader/releases/download/v2.1.2/CssLoader-Standalone.exe

**Comment by GitMuslim** [comment]
> [CSS_Loader] Initializing css loader...
[CSS_Loader] Loaded 32795 css translations from local file
[CSS_Loader] Max supported manifest version: 9
[CSS_Loader] Got win steam install path: 'C:\Program Files (x86)\Steam'
[CSS_Loader] Loading themes...
[CSS_Loader] {}
[CSS_Loader] Not observing themes folder for file changes
[CSS_Loader] Initialized css loader. Found 0 themes. Total 0 injects, 0 injected
[CSS_Loader] Got win steam install path: 'C:\Program Files (x86)\Steam'
[CSS_Loader] Started CSS_Loader server on port 35821
[CSS_Loader] Initializing hook
[CSS_Loader] Got win steam install path: 'C:\Program Files (x86)\Steam'
[CSS_Loader] Fetching CSS mappings from https://api.deckthemes.com/stable.json
======== Running on http://127.0.0.1:35821 ========
(Press CTRL+C to quit)
main.py:281: DeprecationWarning: There is no current event loop
[CSS_Loader] Got win steam install path: 'C:\Program Files (x86)\Steam'
main.py:284: DeprecationWarning: There is no current event loop
[CSS_Loader] Fetched css translations from server
[CSS_Loader] Loaded 32795 css translations from local file
[CSS_Loader] Loading themes...
[CSS_Loader] {}
[CSS_Loader] [FAIL] [css_browserhook.py:437] [Health Check] Cannot connect to host 127.0.0.1:8080 ssl:default [The remote computer refused the network connection]

**Comment by suchmememanyskill** [comment]
This seems like it works then, no? Does it stay in the taskbar?

Maybe worth looking at the .exe in shell:startup (in run dialogue)

**Comment by GitMuslim** [comment]
not sure what you mean by taskbar, the only thing in the taskbar is the terminal/cmd running the app

and btw going to http://127.0.0.1:35821/ just gives `404: Not Found`, as for the shell:startup folder there is nothing in it.

**Comment by GitMuslim** [comment]
actually wait I tried re-launching steam while it's running and now it's connected to it

but it ended up printing this
> Request for Runtime.evaluate took more than 5s. Assuming it failed (17)

**Comment by suchmememanyskill** [comment]
> shell:startup folder there is nothing in it.

Then defender likely deleted it. After running the desktop app you get an .exe there to boot cssloader on startup

For your other issue, no idea. Not enough context. Could be steam bugging out?

**Comment by suchmememanyskill** [comment]
Note: you need to check defender's history to see if it deleted anything

**Comment by GitMuslim** [comment]
yeah ik, defender's history has nothing, it's not doing anything about it.

**Comment by GitMuslim** [comment]
btw there's a try icon now
![image](https://github.com/user-attachments/assets/b39c97c0-1105-4618-b142-8d4d3129fca4)

**Comment by GitMuslim** [comment]
so I tried moving a theme into the folder and it showed this

> [CSS_Loader] Loading themes...
[CSS_Loader] Found theme Round
[CSS_Loader] {'Round': 0}
[CSS_Loader] Loading theme Round

but opening big picture shows nothing different, any idea?

**Comment by suchmememanyskill** [comment]
Does the desktop app not work?

**Comment by GitMuslim** [comment]
> Does the desktop app not work?

I tried clicking the option but the same thing happens, app starts in taskbar for less than a second then closes, could be a GUI library issue maybe?

**Comment by suchmememanyskill** [comment]
Ah ok, i see now. I thought you were talking about the backend appearing in the tray for a second, then dissapearing.

Does event viewer show anything interesting? Is webview2 installed?

Cc @beebls

**Comment by GitMuslim** [comment]
Yes webview was installed

But I seem to have fixed it, I was going to try to build it myself so I installed rust and the rest of deps, but now I tried running the prebuilt app and it worked, thanks anyway! <3
