### ISSUE TITLE
The Backend does not download

### ISSUE THREAD

**Issue by flexadubz** [DeckThemes/CSSLoader-Desktop#38]
Downloading the backend does not complete.
Defender and firewall are not blocking anything, I have tried to use a VPN to other countries to see if this helps but still have the same issue.
Windows Developer Mode is enabled
Temporary solution: Install v1.0.0 and run as administrator (this will install the backend without issues) Then update by restarting the program and clicking "yes" to update. After a restart you will be forced to download the backend again which does not complete.

![downloading the backend](https://github.com/user-attachments/assets/62cd96c1-26b2-4898-b40e-c4b444440e25)

**Comment by beebls** [comment]
This is usually an issue with your AV or windows defender flagging the backend and not letting it download, check windows defender for any blocked files and make sure it isn't being stopped.

Alternatively you can download the backend manually from https://github.com/DeckThemes/SDH-CssLoader/releases (CssLoader-Standalone-Headless), and manually place it in the windows startup directory

**Comment by 2duviz2** [comment]
Happened to me, my fix was disabling WARP (Cloudfare's vpn), github usually blocks requests from vpns
